### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by LittleYang0531** [SonolusHaniwa/world-best-star#1]
# Stellarity 

Stellarity is a Resource Site & Custom Chart Site for [World Dai Star: Dream's Stellarium](https://world-dai-star.com).

Made with ❤ by LittleYang0531.

## Features

**API**

- [x] Sonolus Basic API
- [x] Sonolus Authenticate API
- [x] Uploader API
- [x] Downloader API

**Custom Chart**

- [x] Chart List Page
- [x] Login Page
- [x] Chart Details Editor
- [ ] Like Chart

**Game Information**

- [ ] Bind Game Account¹
- [ ] Activities & Announcement Page
- [ ] Music Details Page
- [ ] Audition Details Page
- [ ] League Details Page
- [ ] Character Details Page
- [ ] Post Details Page
- [ ] Accessory Details Page
- [ ] Photo Details Page
- [ ] Story Details Page
- [ ] Comic Details Page
- [ ] Shop Details Page
- [ ] Gacha Details Page

¹: Experimental features. We **cannot** guarantee that using this feature **will not** result in your account being banned. If you bind your account to this website, it means that you are **aware of the danger** of this feature and **voluntarily** assume all consequences that may arise. This website **will not** be responsible for **any property damage** caused by your use of this feature.

## Architecture

- Master Data Source: [Sirius Decrypted Data](https://github.com/SonolusHaniwa/sirius-decrypted-data)
- Binary Data Storage: OneDrive for Business
- Backend Language: PHP
- Frontend Language: Vue + Vite + JavaScript
- Serverless Function: Vercel
